### ISSUE TITLE
Indexdb link broken re: 404

### ISSUE THREAD

**Issue by tsctm** [hstove/kanstack#1]
Hank, 
I am interested in learning more about the integration of the Bstack and indexdb but the link takes me to a 404 page (https://github.com/hstove/kanstack/blob/master/src/blockstack-db/README.MD).  Thanks for your help.

**Comment by tsctm** [comment]
Is this the link for the above - https://github.com/hstove/kanstack/tree/master/src/blockstack-db?

**Comment by hstove** [comment]
Yes, it is! Thanks for pointing that out. Just fixed it.
